[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
mumbai = "${MUMBAI_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
ethereum = "${MAINNET_RPC_URL}"
bsc = "${BSC_RPC_URL}"

[etherscan]
mumbai = { key = "${MUMBAISCAN_API_KEY}", url = "https://api-testnet.polygonscan.com/api" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
ethereum = { key = "${ETHERSCAN_API_KEY}" }
bsc = { key = "${BSCSCAN_API_KEY}", url = "https://api.bscscan.com/api" }
gnosis = { key = "${GNOSIS_ETHERSCAN_API_KEY}", url = "https://blockscout.com/poa/xdai/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
